### PR TITLE
Restyle components

### PR DESCRIPTION
**Pull request by waterlooSunset**

### CODE REVIEW

**Comment by jbhum** [comment]
Most of these changes are reflected in [#21](https://github.com/open-source-society/ossu-ui/pull/21). The only things that I didn't include were the changes to NavLogo.js because I think we need to be getting the logged in/out state and user info from the props rather than the local storage, as this could cause inconsistencies between those two areas. Other than that the only thing missing is some of the changes to .gitignore.

The reason I manually added all those changes in is because I tried merging multiple times and just couldn't seem to get a clean working merge. So I went through that whole branch and tried to reflect all the changes made so that it was up to date with the routing structure and that was mostly what PR #21 was.

**Comment by jbhum** [comment]
Also, I forgot to remove the instructions for installing semantic. So that still needs to be done.

**Comment by waterlooSunset** [comment]
@jbhum, this pull request should removes the semantic instructions. i see what you're saying about not getting whether the user is logged in from local storage, i've commented out that bit for now. I removed all the leftover semantic bits and made my way through my first merge conflict, whcih was fun practice. Anyway not much has changed, your right.

**Comment by jbhum** [comment]
My congratulations on making it through the conflict I gave up and that's why it got rewritten lol

**Pull request merged**
