### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by SoullessWaffle**
- Update curriculum application link
- Link directly to the Gitflow workflow
- Format code in the Style section with backticks
- Rephrase some stuff
- Fix some typos

### CODE REVIEW

**Comment by jbhum** [comment]
:+1:

**Comment by waterlooSunset** [comment]
:+1:

**Comment by dishark** [comment]
line 7:

do you mind to correct it?

**Comment by SoullessWaffle** [comment]
@dishark what do you mean?

**Pull request merged**
