### PR TITLE
Added favicons for android, ios, osx, windows8 etc

### PR DESCRIPTION
**Pull request by waterlooSunset**
I think some of these could be tweaked for size, some of the windows icons could more promintently display the logo. I used the logo that Eric Douglas has used for the curriculum git hub and facebook.

What does everyone think?

### CODE REVIEW

**Comment by SoullessWaffle** [comment]
Great work!
What are the `mstile` images for and why do they have no background?

**Comment by waterlooSunset** [comment]
@SoullessWaffle mstile is for window metro apps. there background is defined in the xml file i believe. Windows add a subtle gradient to their metro app backgrounds and it would create a sharp line on the icon if background was left in the png. The backgorund color windows is handed is #3498db, the color that Eric Douglas has used for the original logo, and then it does it's windows thing with that color

**Comment by ericdouglas** [comment]
@waterlooSunset great work²! :clap:

**Comment by jdinartejesus** [comment]
Yeah look good :+1:

**Pull request merged**
